--- # USING DEBUG MODULE AT PLAYBOOK EXAMPLE
# parameters: var, msg, verbosity. Print output


- hosts: all
  user: joseph
  become: yes
  gather_facts: yes

  tasks:
    - name: Installing telnet
      yum: pkg={{ item }} state=absent
      with_items:
        - telnet
        - lynx

    - name: List Home
      command: ls -al /home/joseph
      register: result
    - debug: var=result
