--- # Loop playbook
- hosts: apacheweb
  user: joseph
  become: yes
  gather_facts: no

  tasks:
    - name: Add a list of users
      user: name={{ item }} state=present
      with_items:
        - user1
        - user2
        - user3
