# testing handler module.
# Can use "become" and become_mode/method instead of sudo.

- hosts: apacheweb
  user: joseph
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  
  tasks:
    - name: Install Apache Web Server
      yum: name=httpd state=installed
      notify: Restart HTTPD
  
  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted
