--- # 'WHEN' playbook example. Distribution based installation test.

- hosts: all
  user: root
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
    - name: Install apache appropriately to distribution type (Debian/Ubuntu)
      apt: name=apache2 state=latest
      when: ansible_os_family == "Debian"

    - name: Install apache appropriately to distribution type (Redhat/CentOS)
      yum: name=httpd state=latest
      when: ansible_os_family == "RedHat"
