--- # 'WHEN' playbook example. Distribution based installation
- hosts: all
  user: joseph
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Install apache appropriately to distribution type (Debian/Ubuntu)
      apt: name=apache2 state=latest
      when: ansible_os_family == "Debian"

    - name: Install apache appropriately to distribution type (Redhat/CentOS)
      yum: name=httpd state=latest
      when: ansible_os_family == "RedHat"
