- hosts: all
  user: joseph
  sudo: yes
  gather_facts: yes
  tasks:
    - name: Update all packages in VMS
      yum: name='*' state=latest
      register: update
    
    - name: write update log to local file
      # local_action: shell echo `date` >> /home/joseph/ansible_logs/'{{ ansible_hostname }}'.update.log
      # local_action: copy content={{ update }} dest=/home/joseph/ansible_logs/{{ ansible_hostname }}.update.log
      local_action: shell echo `date`, ":\n'{{ update }}'"  >> /home/joseph/ansible_logs/'{{ ansible_hostname }}'.update.log
