---
- hosts: all
  user: joseph
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
    - name: Update all packages in VMS
      yum: name='*' state=latest
      register: update
    
    - name: write update log to local file
      local_action: shell echo `date`, ":\n'{{ update }}'"  >> /home/joseph/ansible_logs/'{{ ansible_hostname }}'.update.log
