---
# tasks file for nfsconfig
#
# --- The appropriate tasks are imported based on Server/Client
# Server tasks: nfsserver.yml
# Client tasks: nfsclient.yml

- name: Configuring NFS Server
  import_tasks: nfsserver.yml
  when: type == "server"


- name: Configuring NFS Client(s)
  import_tasks: nfsclient.yml
  when: type == "client"
